export const colors = [
  { name: "Blue", value: "blue" },
  { name: "White", value: "white" },
  { name: "Yellow", value: "yellow" },
  { name: "Green", value: "green" },
  { name: "Red", value: "red" },
  { name: "Purple", value: "purple" },
  { name: "Brown", value: "brown" },
  { name: "Orange", value: "orange" },
  { name: "Teal", value: "teal" },
  { name: "Cyan", value: "cyan" },
  { name: "Pink", value: "pink" },
  { name: "Indigo", value: "indigo" },
  { name: "Gray", value: "gray" },
  { name: "Black", value: "black" },
  { name: "Gold", value: "gold" },
  { name: "Silver", value: "silver" },
  { name: "Bronze", value: "bronze" },
  { name: "Magenta", value: "magenta" },
  { name: "Lime", value: "lime" },
  { name: "Navy", value: "navy" },
  { name: "Maroon", value: "maroon" },
  { name: "Olive", value: "olive" },
  { name: "Turquoise", value: "turquoise" },
  { name: "Coral", value: "coral" },
  { name: "Salmon", value: "salmon" },
  { name: "Khaki", value: "khaki" },
  { name: "Lavender", value: "lavender" },
  { name: "Peach", value: "peach" },
  { name: "Mint", value: "mint" },
  { name: "Amber", value: "amber" },
  { name: "Beige", value: "beige" },
  { name: "Transparent", value: "transparent" },
];

export const sizeOptions = {
  clothing: ["XS", "S", "M", "L", "XL", "XXL", "XXXL", "XXXXL", "XXXXXL"],
  footwear: Array.from({ length: 14 }, (_, i) => (i + 35).toString()),
  childrenClothing: ["XS", "S", "M", "L", "XL", "XXL", "3XL", "4XL", "5XL"],
  childrenFootwear: Array.from({ length: 18 }, (_, i) => (i + 25).toString()),
  noSize: ["One Size"],
};
